language: python
python:
  - '3.6'
install:
  - python setup.py -q install
after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish
after_failure:
  - dmesg | tail -n 100